### ISSUE TITLE
Wow, a good start. When can we get the Arete Engine? Will there be an editor for the arete engine?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [aretegames/arete-engine#2]

**Comment by jamesordner** [comment]
There won't be an editor at launch, but this is definitely something we want to support.

When the engine is officially released (more or less in its current state, but with more documentation and examples), we will have a trello board or similar with a roadmap, so that everyone can see our upcoming features and help us prioritize them. I'll leave this issue open until we make the roadmap public.
